version: '3.8'

services:
  proxyboard:
    image: lahiru98s/proxyboard:latest
    container_name: proxyboard
    network_mode: host
    volumes:
      - proxyboard-data:/data
    environment:
      - UI_PORT=8088
      - XRAY_DOMAIN=example.com
    restart: unless-stopped

volumes:
  proxyboard-data:
    driver: local
