version: '3.8'

services:
  xray-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xray-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./opt/xray/xray-configs:/etc/xray:ro
      - ./opt/xray/certs:/certs:ro
      - ./opt/xray/logs:/var/log/xray
    environment:
      - XRAY_LOGLEVEL=info
      - TZ=UTC
    stdin_open: true
    tty: true
    cap_add:
      - NET_BIND_SERVICE
